### ISSUE TITLE
Install fails 

### ISSUE THREAD

**Issue by pdamoc** [panosoft/elm-grove#1]
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for @elm-node/core
```

npm version 5.4.2 on node v8.6.0

**Comment by cscalfani** [comment]
This is a known bug in npm version 5.4.2 [\#18434](https://github.com/npm/npm/issues/18434).

You have 3 options:

* Use 5.3.0 which comes with node 8.5.0 which I know works
* Fallback to 5.4.0 which I've read works
* Try 5.5.0 which **may** fix this (I believe is the latest version)

**Comment by pdamoc** [comment]
upgrading to 5.5.0 fixed the issue.

**Comment by alexgig** [comment]
Awesome news. Thanks for letting us know!

**Comment by steerio** [comment]
I have the same issue with both npm 5.5.0 and 5.5.1. Logfile attached.

[2017-10-30T14_05_53_139Z-debug.log](https://github.com/panosoft/elm-grove/files/1427462/2017-10-30T14_05_53_139Z-debug.log)

**Comment by alexgig** [comment]
Hi @steerio,

Ya, turns out npm hasn't got it sorted out yet. We are waiting on this issue in the npm repo to be resolved https://github.com/npm/npm/issues/18434.

Best,
Alex

**Comment by alexgig** [comment]
As a workaround until npm gets patched, I have verified that grove will install under the following versions:

```sh
$ npm -v
5.3.0
$ node -v
v8.8.1
```

**Comment by steerio** [comment]
Thanks! I can confirm that 5.4.0 works too (nodejs version is 8.8.1).

(That is, goes past this issue, because then it fails installing nodegit, due to something that appears to be a bug in that package.)

**Comment by alexgig** [comment]
I believe the node version above resolves the nodegit build error.

**Comment by steerio** [comment]
Indeed, 5.3.0 builds everything just fine. Thanks again!

I think it would be a good idea to make a note of this in the README file, currently it lists npm 5.5.x+ as a requirement.

**Comment by cscalfani** [comment]
Good idea... Readme changed.

**Comment by Tanneguy** [comment]
I have a build failure on 
- node v8.9.1
- npm v5.3.0
As the current version of node (as per `apt-get install nodejs `) is v8.9.1 I would mention that in the Readme

**Comment by leefr** [comment]
Running the following to get to 5.6.0 seems to really resolve the issue, at least for now:
`npm install npm@next -g`
