### ISSUE TITLE
Can't get grove docs to work

### ISSUE THREAD

**Issue by ghivert** [panosoft/elm-grove#13]
Hi.

Grove's awesome, but I can't get `grove docs` to work in the latest version of [elegant](https://github.com/elm-bodybuilder/elegant). It seems to work, but I finally get an error `BUG: non-unique name`. I can paste the entire error message, but I don't think it's useful.

Any idea ? Maybe a problem with my code ?

**Comment by alexgig** [comment]
Hi @ghivert,

We've been able to reproduce the issue and are looking in to it.

Thanks

**Comment by alexgig** [comment]
Hi @ghivert,

A few of your files have duplicate entries for some values in the Module comment block `@docs` declarations. As a workaround, removing those duplicates will allow you to build the docs. 

`src/elegant/Grid.elm`:
- `align`

`src/elegant/Elegant.elm`:
- `Modifier`

`src/elegant/Elegant.elm`:
- `block`

**Comment by ghivert** [comment]
Thanks, that's awesome!

I thought the elm compiler would check for that, but it doesn't apparently. I think it would be so cool that Grove display a more explaining error, because it doesn't even indicates a file where it fails.

**Comment by alexgig** [comment]
Created https://github.com/panosoft/elm-docs/issues/1 to address this.

**Comment by alexgig** [comment]
You're welcome, Guillaume.

We'll look into a better error message, or maybe not error-ing out at all.

Best,
Alexandre

**Comment by ghivert** [comment]
I'll be looking for improvements! ;)

Thanks for all again!

**Comment by alexgig** [comment]
You're welcome.

**Comment by cscalfani** [comment]
This has been fixed in 1.2.1.

**Comment by alexgig** [comment]
FYI: The fix was to not error-out at all. Now, grove will respect all your `@docs` tags and render docs as specified, even if the same value is included in multiple `@docs` declarations.

i.e.
```
{-| Module comment.

@docs value
@docs value
-}
```

Will include docs for `value` twice.

Best,
Alex
