### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by ssoshchepkov** [panosoft/elm-grove#19]
Hello!

I’m trying to install `elm-websocket-client` with elm-grove.
After typing `grove install panosoft/elm-websocket-client` in my working directory it started to clone the dependencies and I’ve got errors like this: 
`ERROR: Unable to clone: elm-community/json-extra Error: Unable to clone: https://github.com/elm-community/json-extra.git (Error: failed to make directory 'C:\Users\my_username\AppData\Local\Temp\elm-community\json-extra': The system cannot find the path specified.
)`
for all of them.

After a little investigation I found out that `Nodegit` wants only forward-slashes for directory separators no matter what OS is used.
I’ve converted backward-slashes to forward-slashes for `cloneLocation` here: https://github.com/panosoft/elm-grove/blob/8188f77a1688f407703d90aca0b3d799c30014f9/src/Native/Git.js#L30
All dependencies were cloned; it started to check out and got frozen:
`Cloning https://github.com/elm-community/json-extra.git`
`Cloning https://github.com/elm-lang/core.git`
`Cloning https://github.com/elm-lang/html.git`
`Cloning https://github.com/elm-lang/websocket.git`
`Cloning https://github.com/justinmimbs/elm-date-extra.git`
`Cloning https://github.com/panosoft/elm-websocket-client.git`
`Checking out: panosoft/elm-websocket-client (6.0.1)`
`Checking out: elm-lang/websocket (1.0.2)`
`Checking out: elm-community/json-extra (2.6.0)`
`Checking out: justinmimbs/elm-date-extra (3.0.0)`
`Checking out: elm-lang/html (2.0.0)`
`Checking out: elm-lang/core (5.1.1)`

After further investigation I saw that the destination paths for checkout looked like `D:\_projects\my_work_directory\C:/Users/my_username/AppData/Local/Temp/elm-lang/html\2.0.0`
So I’ve looked at `pathJoin` function: https://github.com/panosoft/elm-grove/blob/8188f77a1688f407703d90aca0b3d799c30014f9/src/AppUtils.elm#L48-L59 and found out that it determines whatever path is absolute or not incorrectly on Windows. I’ve made it more Windows friendly and the destination paths changed to something like `C:/Users/my_username/AppData/Local/Temp/elm-lang/html\2.0.0` not sure if that’s a correct behavior or not, though. 

Now it crushes with` ERROR: Unable to read: elm-package.json location: C:/Users/my_username/AppData/Local/Temp/elm-lang/html\elm-package.json Error: SystemError NoSuchFileOrDirectory { message = "ENOENT: no such file or directory, open 'C:\\Users\\my_username\\AppData\\Local\\Temp\\elm-lang\\html\\elm-package.json'", stack = "Error: ENOENT: no such file or directory, open 'C:\\Users\\my_username\\AppData\\Local\\Temp\\elm-lang\\html\\elm-package.json'", syscall = "open", path = Just "C:\\Users\\my_username\\AppData\\Local\\Temp\\elm-lang\\html\\elm-package.json", address = Nothing, port_ = Nothing } ` and here I give up. Could you please provide any clue on what’s going on?

**Comment by cscalfani** [comment]
The only thing I can see here is that the filename has all forward slashes in it except for the last one:

```C:/Users/my_username/AppData/Local/Temp/elm-lang/html\elm-package.json```

You now have more experience with running this on Windows than I do at this point.

BTW, I'm no longer maintaining this project due to the fact that Evan has vowed to disallow Native code in Elm 0.19. We are no longer using Elm for server code.

**Comment by ssoshchepkov** [comment]
Oh, thanks for the information. I think i'll suspend my Elm studies then and switch to Fable or ScalaJs.

**Comment by cscalfani** [comment]
We've moved to Haskell on the backend and are still using Elm on the frontend (for now). I will be looking to Purescript or Haskell (GHCJS or WebAssembly) in the future.

I don't want to discourage you from learning Elm. I think it's a great gateway into Haskell.

Using it in production is another thing all together. I would use it carefully.

As far as websockets go, you can always use the Elm websocket library.

**Comment by ssoshchepkov** [comment]
I’m searching for a saner alternative to JS/Typescript on the frontend.

I’ve tried Elm websocket library, but it lacks subscriptions on connect/reconnect. A had a choice to use WebSocket.LowLevel or elm-websocket-client. The latter seemed more pragmatic but it did not end well. At the same time it’s highly frustrating to see that issues and PRs on this topic on the websocket library repository remain unaddressed by maintainers for a pretty long time.

For now Elm seems to me as a nice language with a very poorly maintained ecosystem. I’ll definitely keep an eye on it, but for now I think I should try something else.
