### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by AIRTucha** [panosoft/elm-grove#20]
Hi, thank you very much for a great project. I was wondering, why isn't it available on npm?

**Comment by cscalfani** [comment]
There's no reason to have it on `npm` since you can install it from Github. Also, do not use this if you are planning on upgrading to Elm 0.19 because Evan has made changes to prevent the use of this package manager, viz. disallowing Native code.

**Comment by AIRTucha** [comment]
@cscalfani, thanks for your response. I was working on a back-end framework for Elm, which includes some native code and I got disapproval from Evan, so your package manager is the only option for me to finish the project at least in some way.

**Comment by cscalfani** [comment]
Depending on what you're doing, you may consider using `ports`. Having said that, we couldn't easily write `grove` using ports because they return `Cmd msg` instead of `Tasks`.

We abandoned over 30,000 lines of backend code in Elm and moved our backend code to Haskell.

**Comment by AIRTucha** [comment]
Oh, that is a lot. I was just having fun. An idea was to combine Haskell-like tool with Node.js deployment ecosystem. But I think PureScript seems to be a better choice)

**Comment by tad-lispy** [comment]
@cscalfani AFAIK the native modules will be forbidden in Elm 0.19, but Grove seems to enable other useful features, e.g. private and local packages. This should not be affected, right?

**Comment by cscalfani** [comment]
I can't say. There could be some changes made that breaks other things. Also, the elm-package manager might allow private repos, who knows. Either way, I've stopped maintaining this, so if something breaks, you can fork this and fix it (if you like). But remember to build it under 0.18.
