### ISSUE TITLE
Support pre-release versions

### ISSUE THREAD

**Issue by alexgig** [panosoft/elm-grove#6]
Add support for `--alpha`, `--beta`, and `--rc` flags when using `grove bump`.

Ref:
- http://semver.org/#spec-item-9
- http://semver.org/#spec-item-11

**Comment by alexgig** [comment]
Elm compiler does not currently support pre-release versions so this is not possible at the moment.

**Comment by cscalfani** [comment]
The best way to have someone else test a package prior to its release, at the moment, is to push to a separate branch, i.e. `next`, then have them clone/pull the repo, checkout that branch and use the `--link` option on `grove install` to install in locally. Don't forget to properly set the `grove-links.json` file.
